# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket <YOUR_S3_BUCKET> --output-template-file packaged-template.yaml

artifacts:
  files:
    - packaged-template.yaml
