version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run build
      - zip -r my-function.zip *
  post_build:
    commands:
      - mv my-function.zip ../
artifacts:
  files:
    - ../my-function.zip
